@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

### register a team
POST {{host}}/api/v1/auth/signup {{http}}
Content-Type: {{contentType}}

{
    "team_name": "EvoTech",
    "email": "shavinanjithachandrawansha@gmail.com",
    "password": "12345678"
}

### verify an account
@token =  50792d22f4f9b0ffc1dfea59f5611f6392cdd20c
@team_name = EvoTech
POST {{host}}/api/v1/auth/verify/{{team_name}}/{{token}} {{http}}

### login to the team account
POST {{host}}/api/v1/auth/login {{http}}
Content-Type: {{contentType}}

{
    "email": "shavinanjithachandrawansha@gmail.com",
    "password": "12345678"
}


### create a admin account
POST {{host}}/api/v1/auth/signup/admin {{http}}
Content-Type: {{contentType}}

{
    "team_name": "root_1",
    "email": "root1@gmail.com",
    "password": "12345678"
}