@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

### register a team
POST {{host}}/api/v1/auth/signup {{http}}
Content-Type: {{contentType}}

{
    "team_name": "EvoTech",
    "email": "shavinanjithachandrawansha@gmail.com",
    "password": "12345678"
}

### root

POST {{host}}/api/v1/auth/login {{http}}
Content-Type: {{contentType}}

{
    "email": "shavin@gmail.com",
    "password": "rootrootroot"
}

### verify an account
@token =  50792d22f4f9b0ffc1dfea59f5611f6392cdd20c
@team_name = EvoTech
POST {{host}}/api/v1/auth/verify/{{team_name}}/{{token}} {{http}}

### login to the team account
POST {{host}}/api/v1/auth/login {{http}}
Content-Type: {{contentType}}

{
    "email": "pytha@gmail.com",
    "password": "987654321"
}


### create a admin account
POST {{host}}/api/v1/auth/signup/admin {{http}}
Content-Type: {{contentType}}

{
    "team_name": "root_1",
    "email": "root1@gmail.com",
    "password": "12345678"
}


### reset password
@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFtX25hbWUiOiJQeXRoYSIsInRlYW1faWQiOjEwLCJyb2xlIjoidGVhbSIsImlhdCI6MTcwODUyMjc0NywiZXhwIjoxNzA4NjA5MTQ3fQ.AMSfinP13ZNe41lvBI8dQ8QI6_ETtG0c2OAr8mmqMb8
POST {{host}}/api/v1/auth/reset {{http}}
Content-Type: {{contentType}}
x-auth-token: {{token1}}

{
    "old_password": "987654321",
    "new_password": "123456789"
}

### forget password
POST {{host}}/api/v1/auth/forget-password {{http}}
Content-Type: {{contentType}}

{
    "email" : "shavinanjithachandrawansha@gmail.com"
}

### reset fotget password
@token=413ba4b006a1fd2cdd7092a4875d18134ca9b9a
@team_id=2
POST {{host}}/api/v1/auth/forget-password/reset/{{team_id}}/{{token}} {{http}}
Content-Type: {{contentType}}

{
    "password" : "12345678"
}